const SPLASH ="/";
const LOGIN ="/login";
const REGISTER ="/register";
const DASHBOARD = "/dashboard";
const HOME = "/home";
const FAVORITE = "/favorite";
const PRODUCT = "/product";
const CART = "/cart";
const PROFILE = "/profile";